import database.chapters.chapter_lengths as chapter_lengths

postanak_lengths = chapter_lengths.get_chapters_from_book_name("postanak")
izlazak_lengths = chapter_lengths.get_chapters_from_book_name("izlazak")
levitski_zakonik_lengths = chapter_lengths.get_chapters_from_book_name("levitski_zakonik")
brojevi_lengths = chapter_lengths.get_chapters_from_book_name("brojevi")
ponovljeni_zakon_lengths = chapter_lengths.get_chapters_from_book_name("ponovljeni_zakon")
josua_lengths = chapter_lengths.get_chapters_from_book_name("josua")
suci_lengths = chapter_lengths.get_chapters_from_book_name("suci")
ruta_lengths = chapter_lengths.get_chapters_from_book_name("ruta")
samuel1_lengths = chapter_lengths.get_chapters_from_book_name("samuel1")
samuel2_lengths = chapter_lengths.get_chapters_from_book_name("samuel2")
kraljevi1_lengths = chapter_lengths.get_chapters_from_book_name("kraljevi1")
kraljevi2_lengths = chapter_lengths.get_chapters_from_book_name("kraljevi2")
ljetopisi1_lengths = chapter_lengths.get_chapters_from_book_name("ljetopisi1")
ljetopisi2_lengths = chapter_lengths.get_chapters_from_book_name("ljetopisi2")
ezra_lengths = chapter_lengths.get_chapters_from_book_name("ezra")
nehemija_lengths = chapter_lengths.get_chapters_from_book_name("nehemija")
estera_lengths = chapter_lengths.get_chapters_from_book_name("estera")
job_lengths = chapter_lengths.get_chapters_from_book_name("job")
psalmi_lengths = chapter_lengths.get_chapters_from_book_name("psalmi")
mudre_izreke_lengths = chapter_lengths.get_chapters_from_book_name("mudre_izreke")
propovjednik_lengths = chapter_lengths.get_chapters_from_book_name("propovjednik")
pjesma_nad_pjesmama_lengths = chapter_lengths.get_chapters_from_book_name("pjesma_nad_pjesmama")
izaija_lengths = chapter_lengths.get_chapters_from_book_name("izaija")
jeremija_lengths = chapter_lengths.get_chapters_from_book_name("jeremija")
tuzaljke_lengths = chapter_lengths.get_chapters_from_book_name("tuzaljke")
ezekiel_lengths = chapter_lengths.get_chapters_from_book_name("ezekiel")
daniel_lengths = chapter_lengths.get_chapters_from_book_name("daniel")
hosea_lengths = chapter_lengths.get_chapters_from_book_name("hosea")
joel_lengths = chapter_lengths.get_chapters_from_book_name("joel")
amos_lengths = chapter_lengths.get_chapters_from_book_name("amos")
obadija_lengths = chapter_lengths.get_chapters_from_book_name("obadija")
jona_lengths = chapter_lengths.get_chapters_from_book_name("jona")
mihej_lengths = chapter_lengths.get_chapters_from_book_name("mihej")
nahum_lengths = chapter_lengths.get_chapters_from_book_name("nahum")
habakuk_lengths = chapter_lengths.get_chapters_from_book_name("habakuk")
sefanija_lengths = chapter_lengths.get_chapters_from_book_name("sefanija")
hagaj_lengths = chapter_lengths.get_chapters_from_book_name("hagaj")
zaharija_lengths = chapter_lengths.get_chapters_from_book_name("zaharija")
malahija_lengths = chapter_lengths.get_chapters_from_book_name("malahija")

# ID number, book name (internal), full name (title), old_testament, book length
postanak = (1, "postanak", "Postanak", "old_testament", postanak_lengths)
izlazak = (2, "izlazak", "Knjiga Izlaska", "old_testament", izlazak_lengths)
levitski_zakonik = (3, "levitski_zakonik", "Levitski zakonik", "old_testament", levitski_zakonik_lengths)
brojevi = (4, "brojevi", "Knjiga brojeva", "old_testament", brojevi_lengths)
ponovljeni_zakon = (5, "ponovljeni_zakon", "Ponovljeni zakon", "old_testament", ponovljeni_zakon_lengths)
josua = (6, "josua", "Jošua", "old_testament", josua_lengths)
suci = (7, "suci", "Knjiga o sucima", "old_testament", suci_lengths)
ruta = (8, "ruta", "Ruta", "old_testament", ruta_lengths)
samuel1 = (9, "samuel1", "Prva knjiga o Samuelu", "old_testament", samuel1_lengths)
samuel2 = (10, "samuel2", "Druga knjiga o Samuelu", "old_testament", samuel2_lengths)
kraljevi1 = (11, "kraljevi1", "Prva knjiga o kraljevima", "old_testament", kraljevi1_lengths)
kraljevi2 = (12, "kraljevi2", "Druga knjiga o kraljevima", "old_testament", kraljevi2_lengths)
ljetopisi1 = (13, "ljetopisi1", "Prva knjiga Ljetopisa", "old_testament", ljetopisi1_lengths)
ljetopisi2 = (14, "ljetopisi2", "Druga knjiga Ljetopisa", "old_testament", ljetopisi2_lengths)
ezra = (15, "ezra", "Knjiga Ezrina", "old_testament", ezra_lengths)
nehemija = (16, "nehemija", "Knjiga Nehemijina", "old_testament", nehemija_lengths)
estera = (19, "estera", "Estera", "old_testament", estera_lengths)
job = (22, "job", "Knjiga o Jobu", "old_testament", job_lengths)
psalmi = (23, "psalmi", "Psalmi", "old_testament", psalmi_lengths)
mudre_izreke = (24, "mudre_izreke", "Mudre izreke", "old_testament", mudre_izreke_lengths)
propovjednik = (25, "propovjednik", "Propovjednik", "old_testament", propovjednik_lengths)
pjesma_nad_pjesmama = (26, "pjesma_nad_pjesmama", "Pjesma nad pjesmama", "old_testament", pjesma_nad_pjesmama_lengths)
izaija = (29, "izaija", "Izaija", "old_testament", izaija_lengths)
jeremija = (30, "jeremija", "Jeremija", "old_testament", jeremija_lengths)
tuzaljke = (31, "tuzaljke", "Tužaljke", "old_testament", tuzaljke_lengths)
ezekiel = (33, "ezekiel", "Ezekiel", "old_testament", ezekiel_lengths)
daniel = (34, "daniel", "Daniel", "old_testament", daniel_lengths)
hosea = (35, "hosea", "Hošea", "old_testament", hosea_lengths)
joel = (36, "joel", "Joel", "old_testament", joel_lengths)
amos = (37, "amos", "Amos", "old_testament", amos_lengths)
obadija = (38, "obadija", "Obadija", "old_testament", obadija_lengths)
jona = (39, "jona", "Jona", "old_testament", jona_lengths)
mihej = (40, "mihej", "Mihej", "old_testament", mihej_lengths)
nahum = (41, "nahum", "Nahum", "old_testament", nahum_lengths)
habakuk = (42, "habakuk", "Habakuk", "old_testament", habakuk_lengths)
sefanija = (43, "sefanija", "Sefanija", "old_testament", sefanija_lengths)
hagaj = (44, "hagaj", "Hagaj", "old_testament", hagaj_lengths)
zaharija = (45, "zaharija", "Zaharija", "old_testament", zaharija_lengths)
malahija = (46, "malahija", "Malahija", "old_testament", malahija_lengths)

old_testament_books = []
old_testament_books.append(postanak)
old_testament_books.append(izlazak)
old_testament_books.append(levitski_zakonik)
old_testament_books.append(brojevi)
old_testament_books.append(ponovljeni_zakon)
old_testament_books.append(josua)
old_testament_books.append(suci)
old_testament_books.append(ruta)
old_testament_books.append(samuel1)
old_testament_books.append(samuel2)
old_testament_books.append(kraljevi1)
old_testament_books.append(kraljevi2)
old_testament_books.append(ljetopisi1)
old_testament_books.append(ljetopisi2)
old_testament_books.append(ezra)
old_testament_books.append(nehemija)
old_testament_books.append(estera)
old_testament_books.append(job)
old_testament_books.append(psalmi)
old_testament_books.append(mudre_izreke)
old_testament_books.append(propovjednik)
old_testament_books.append(pjesma_nad_pjesmama)
old_testament_books.append(izaija)
old_testament_books.append(jeremija)
old_testament_books.append(tuzaljke)
old_testament_books.append(ezekiel)
old_testament_books.append(daniel)
old_testament_books.append(hosea)
old_testament_books.append(joel)
old_testament_books.append(amos)
old_testament_books.append(obadija)
old_testament_books.append(jona)
old_testament_books.append(mihej)
old_testament_books.append(nahum)
old_testament_books.append(habakuk)
old_testament_books.append(sefanija)
old_testament_books.append(hagaj)
old_testament_books.append(zaharija)
old_testament_books.append(malahija)

def get_books():
    return old_testament_books

def get_books_names():
    old_testament_books_names = []
    for book in old_testament_books:
        name = book[2]
        old_testament_books_names.append(name)
        
    return old_testament_books_names

def get_book_by_title(book_title):
    for book in old_testament_books:
        title = book[2]
        if title == book_title:
            return book
        
    return None